
# Standard defs:
OBJS = $(SRCS:.hs=.o)
GHC  = ghc
CC   = gcc
RM   = rm -f

BASICFLAGS = -fglasgow-exts \
	     -fallow-overlapping-instances \
	     -fallow-undecidable-instances

FLAGS = $(BASICFLAGS)

# Specific

SRCS =	Basics.hs \
	DebugT.hs \
	EnvT.hs \
	Error.hs \
	ErrorT.hs \
	Fix.hs \
	HasName.hs \
	HasParser.hs \
	Heap.hs \
	IOT.hs \
	IOUtils.hs \
	Id.hs \
	Initial.hs \
	Interp.hs \
	MFix.hs \
	Main.hs \
	Memory.hs \
	MonadT.hs \
	ParseLib.hs \
	ParserUtils.hs \
	SFunctor.hs \
	SemMonad.hs \
	ShowMonad.hs \
	ShowUtils.hs \
	StateT.hs \
	SubType.hs \
	Table.hs \
	TermB.hs \
	TermCMP.hs \
	TermD.hs \
	TermF.hs \
	TermN.hs \
	TermP.hs \
	TermR.hs \
	TermV.hs 

OBJS = 	Basics.o \
	DebugT.o \
	EnvT.o \
	Error.o \
	ErrorT.o \
	Fix.o \
	HasName.o \
	HasParser.o \
	Heap.o \
	IOUtils.o \
	IOT.o \
	Id.o \
	Initial.o \
	Interp.o \
	MFix.o \
	Main.o \
	Memory.o \
	MonadT.o \
	ParseLib.o \
	ParserUtils.o \
	SFunctor.o \
	SemMonad.o \
	ShowMonad.o \
	ShowUtils.o \
	StateT.o \
	SubType.o \
	Table.o \
	TermB.o \
	TermCMP.o \
	TermD.o \
	TermF.o \
	TermN.o \
	TermP.o \
	TermR.o \
	TermV.o 

mods : $(OBJS)
	$(RM) $@
	$(GHC) -o $@ $(FLAGS) $(OBJS)

### Boilerplate GHC stuff

.SUFFIXES	: .lhs .hs .hi .o

depend :: 	$(SRC)
		$(GHC) -M $(DEPENDFLAGS) $(SRCS)

clean ::
	$(RM) *.o *.hi *.exe *~

%.hi		: %.o
		@:

%.o		: %.hs
		$(RM) $@
		$(GHC) $(FLAGS) -c $< 

# DO NOT DELETE: Beginning of Haskell dependencies
EnvT.o : EnvT.hs
EnvT.o : ./MonadT.hi
EnvT.o : ./ShowMonad.hi
EnvT.o : ./Initial.hi
Error.o : Error.hs
ErrorT.o : ErrorT.hs
ErrorT.o : ./MonadT.hi
ErrorT.o : ./ShowMonad.hi
ErrorT.o : ./Id.hi
ErrorT.o : ./Error.hi
Fix.o : Fix.hs
HasName.o : HasName.hs
HasName.o : ./SubType.hi
HasParser.o : HasParser.hs
HasParser.o : ./ParseLib.hi
HasParser.o : ./Fix.hi
IOT.o : IOT.hs
IOT.o : ./Basics.hi
IOT.o : ./Initial.hi
IOT.o : ./MonadT.hi
IOT.o : ./ShowMonad.hi
IOT.o : ./ShowUtils.hi
IOT.o : ./StateT.hi
IOUtils.o : IOUtils.hs
Id.o : Id.hs
Id.o : ./ShowMonad.hi
Initial.o : Initial.hs
Interp.o : Interp.hs
Interp.o : ./Fix.hi
Interp.o : ./MFix.hi
MFix.o : MFix.hs
MFix.o : ./Fix.hi
Main.o : Main.hs
Main.o : ./Heap.hi
Main.o : ./Fix.hi
Main.o : ./TermN.hi
Main.o : ./TermV.hi
Main.o : ./TermB.hi
Main.o : ./TermCMP.hi
Main.o : ./TermR.hi
Main.o : ./TermP.hi
Main.o : ./TermF.hi
Main.o : ./TermD.hi
Main.o : ./Table.hi
Main.o : ./EnvT.hi
Main.o : ./DebugT.hi
Main.o : ./StateT.hi
Main.o : ./ErrorT.hi
Main.o : ./IOT.hi
Main.o : ./Id.hi
Main.o : ./HasName.hi
Main.o : ./Initial.hi
Main.o : ./SubType.hi
Main.o : ./Error.hi
Main.o : ./SFunctor.hi
Main.o : ./Interp.hi
Main.o : ./HasParser.hi
Main.o : ./ParseLib.hi
Main.o : ./IOUtils.hi
Main.o : ./Interp.hi
Main.o : ./SubType.hi
Main.o : ./HasName.hi
Main.o : ./Heap.hi
Main.o : ./Initial.hi
Main.o : ./Fix.hi
Main.o : ./MFix.hi
Main.o : ./ParseLib.hi
Main.o : ./HasParser.hi
Main.o : ./SFunctor.hi
Main.o : ./Error.hi
Main.o : ./Table.hi
Main.o : ./DebugT.hi
Main.o : ./EnvT.hi
Main.o : ./IOT.hi
Main.o : ./ErrorT.hi
Main.o : ./StateT.hi
Main.o : ./TermN.hi
Main.o : ./TermB.hi
Main.o : ./TermCMP.hi
Main.o : ./TermV.hi
Main.o : ./TermP.hi
Main.o : ./TermR.hi
Main.o : ./TermF.hi
Main.o : ./TermD.hi
Main.o : ./IOUtils.hi
Main.o : ./Id.hi
MonadT.o : MonadT.hs
ParseLib.o : ParseLib.hs
ParserUtils.o : ParserUtils.hs
ParserUtils.o : ./ParseLib.hi
SFunctor.o : SFunctor.hs
SFunctor.o : ./SubType.hi
SFunctor.o : ./Fix.hi
SFunctor.o : ./MFix.hi
SemMonad.o : SemMonad.hs
SemMonad.o : ./HasName.hi
SemMonad.o : ./ErrorT.hi
SemMonad.o : ./SubType.hi
ShowMonad.o : ShowMonad.hs
ShowUtils.o : ShowUtils.hs
StateT.o : StateT.hs
StateT.o : ./MonadT.hi
StateT.o : ./ShowMonad.hi
StateT.o : ./Initial.hi
SubType.o : SubType.hs
Table.o : Table.hs
Table.o : ./ErrorT.hi
Table.o : ./Initial.hi
Table.o : ./Basics.hi
TermB.o : TermB.hs
TermB.o : ./Fix.hi
TermB.o : ./MFix.hi
TermB.o : ./SubType.hi
TermB.o : ./ErrorT.hi
TermB.o : ./HasName.hi
TermB.o : ./SemMonad.hi
TermB.o : ./ParseLib.hi
TermB.o : ./HasParser.hi
TermB.o : ./ShowUtils.hi
TermCMP.o : TermCMP.hs
TermCMP.o : ./Fix.hi
TermCMP.o : ./MFix.hi
TermCMP.o : ./SubType.hi
TermCMP.o : ./ErrorT.hi
TermCMP.o : ./HasName.hi
TermCMP.o : ./SemMonad.hi
TermCMP.o : ./ParseLib.hi
TermCMP.o : ./HasParser.hi
TermCMP.o : ./ShowUtils.hi
TermD.o : TermD.hs
TermD.o : ./Basics.hi
TermD.o : ./Fix.hi
TermD.o : ./MFix.hi
TermD.o : ./SubType.hi
TermD.o : ./ErrorT.hi
TermD.o : ./StateT.hi
TermD.o : ./EnvT.hi
TermD.o : ./HasName.hi
TermD.o : ./SemMonad.hi
TermD.o : ./ParseLib.hi
TermD.o : ./HasParser.hi
TermD.o : ./ShowUtils.hi
TermD.o : ./Heap.hi
TermD.o : ./Table.hi
TermF.o : TermF.hs
TermF.o : ./Fix.hi
TermF.o : ./Basics.hi
TermF.o : ./HasName.hi
TermF.o : ./MFix.hi
TermF.o : ./SubType.hi
TermF.o : ./ErrorT.hi
TermF.o : ./StateT.hi
TermF.o : ./EnvT.hi
TermF.o : ./Table.hi
TermF.o : ./Heap.hi
TermF.o : ./SemMonad.hi
TermF.o : ./ParseLib.hi
TermF.o : ./HasParser.hi
TermF.o : ./IOT.hi
TermN.o : TermN.hs
TermN.o : ./Id.hi
TermN.o : ./Fix.hi
TermN.o : ./SubType.hi
TermN.o : ./ErrorT.hi
TermN.o : ./HasName.hi
TermN.o : ./SemMonad.hi
TermN.o : ./ParseLib.hi
TermN.o : ./ShowUtils.hi
TermN.o : ./HasParser.hi
TermN.o : ./MFix.hi
TermN.o : ./Fix.hi
TermP.o : TermP.hs
TermP.o : ./Basics.hi
TermP.o : ./Fix.hi
TermP.o : ./MFix.hi
TermP.o : ./SubType.hi
TermP.o : ./ErrorT.hi
TermP.o : ./StateT.hi
TermP.o : ./EnvT.hi
TermP.o : ./IOT.hi
TermP.o : ./Table.hi
TermP.o : ./Heap.hi
TermP.o : ./HasName.hi
TermP.o : ./ParseLib.hi
TermP.o : ./HasParser.hi
TermP.o : ./SemMonad.hi
TermR.o : TermR.hs
TermR.o : ./HasName.hi
TermR.o : ./StateT.hi
TermR.o : ./Fix.hi
TermR.o : ./MFix.hi
TermR.o : ./SubType.hi
TermR.o : ./ErrorT.hi
TermR.o : ./ParseLib.hi
TermR.o : ./ShowUtils.hi
TermR.o : ./HasParser.hi
TermR.o : ./Basics.hi
TermR.o : ./Heap.hi
TermR.o : ./SemMonad.hi
TermV.o : TermV.hs
TermV.o : ./Basics.hi
TermV.o : ./HasName.hi
TermV.o : ./StateT.hi
TermV.o : ./Fix.hi
TermV.o : ./MFix.hi
TermV.o : ./SubType.hi
TermV.o : ./ErrorT.hi
TermV.o : ./EnvT.hi
TermV.o : ./Table.hi
TermV.o : ./Heap.hi
TermV.o : ./SemMonad.hi
TermV.o : ./ParseLib.hi
TermV.o : ./HasParser.hi
TermV.o : ./IOT.hi
# DO NOT DELETE: End of Haskell dependencies
# DO NOT DELETE: Beginning of Haskell dependencies
Basics.o : Basics.hs
EnvT.o : EnvT.hs
EnvT.o : ./MonadT.hi
EnvT.o : ./ShowMonad.hi
EnvT.o : ./Initial.hi
Error.o : Error.hs
ErrorT.o : ErrorT.hs
ErrorT.o : ./MonadT.hi
ErrorT.o : ./ShowMonad.hi
ErrorT.o : ./Id.hi
ErrorT.o : ./Error.hi
Fix.o : Fix.hs
HasName.o : HasName.hs
HasName.o : ./SubType.hi
HasParser.o : HasParser.hs
HasParser.o : ./ParseLib.hi
HasParser.o : ./Fix.hi
IOT.o : IOT.hs
IOT.o : ./Basics.hi
IOT.o : ./Initial.hi
IOT.o : ./MonadT.hi
IOT.o : ./ShowMonad.hi
IOT.o : ./ShowUtils.hi
IOT.o : ./StateT.hi
IOUtils.o : IOUtils.hs
Id.o : Id.hs
Id.o : ./ShowMonad.hi
Initial.o : Initial.hs
Interp.o : Interp.hs
Interp.o : ./Fix.hi
Interp.o : ./MFix.hi
MFix.o : MFix.hs
MFix.o : ./Fix.hi
Main.o : Main.hs
Main.o : ./Heap.hi
Main.o : ./Fix.hi
Main.o : ./TermN.hi
Main.o : ./TermV.hi
Main.o : ./TermB.hi
Main.o : ./TermCMP.hi
Main.o : ./TermR.hi
Main.o : ./TermP.hi
Main.o : ./TermF.hi
Main.o : ./TermD.hi
Main.o : ./Table.hi
Main.o : ./EnvT.hi
Main.o : ./DebugT.hi
Main.o : ./StateT.hi
Main.o : ./ErrorT.hi
Main.o : ./IOT.hi
Main.o : ./Id.hi
Main.o : ./HasName.hi
Main.o : ./Initial.hi
Main.o : ./SubType.hi
Main.o : ./Error.hi
Main.o : ./SFunctor.hi
Main.o : ./Interp.hi
Main.o : ./HasParser.hi
Main.o : ./ParseLib.hi
Main.o : ./IOUtils.hi
Main.o : ./Interp.hi
Main.o : ./SubType.hi
Main.o : ./HasName.hi
Main.o : ./Heap.hi
Main.o : ./Initial.hi
Main.o : ./Fix.hi
Main.o : ./MFix.hi
Main.o : ./ParseLib.hi
Main.o : ./HasParser.hi
Main.o : ./SFunctor.hi
Main.o : ./Error.hi
Main.o : ./Table.hi
Main.o : ./DebugT.hi
Main.o : ./EnvT.hi
Main.o : ./IOT.hi
Main.o : ./ErrorT.hi
Main.o : ./StateT.hi
Main.o : ./TermN.hi
Main.o : ./TermB.hi
Main.o : ./TermCMP.hi
Main.o : ./TermV.hi
Main.o : ./TermP.hi
Main.o : ./TermR.hi
Main.o : ./TermF.hi
Main.o : ./TermD.hi
Main.o : ./IOUtils.hi
Main.o : ./Id.hi
MonadT.o : MonadT.hs
ParseLib.o : ParseLib.hs
ParserUtils.o : ParserUtils.hs
ParserUtils.o : ./ParseLib.hi
SFunctor.o : SFunctor.hs
SFunctor.o : ./SubType.hi
SFunctor.o : ./HasParser.hi
SFunctor.o : ./ParseLib.hi
SFunctor.o : ./Fix.hi
SFunctor.o : ./MFix.hi
SemMonad.o : SemMonad.hs
SemMonad.o : ./HasName.hi
SemMonad.o : ./ErrorT.hi
SemMonad.o : ./SubType.hi
ShowMonad.o : ShowMonad.hs
ShowUtils.o : ShowUtils.hs
StateT.o : StateT.hs
StateT.o : ./MonadT.hi
StateT.o : ./ShowMonad.hi
StateT.o : ./Initial.hi
SubType.o : SubType.hs
Table.o : Table.hs
Table.o : ./ErrorT.hi
Table.o : ./Initial.hi
Table.o : ./Basics.hi
TermB.o : TermB.hs
TermB.o : ./Fix.hi
TermB.o : ./MFix.hi
TermB.o : ./SubType.hi
TermB.o : ./ErrorT.hi
TermB.o : ./HasName.hi
TermB.o : ./SemMonad.hi
TermB.o : ./ParseLib.hi
TermB.o : ./HasParser.hi
TermB.o : ./ShowUtils.hi
TermCMP.o : TermCMP.hs
TermCMP.o : ./Fix.hi
TermCMP.o : ./MFix.hi
TermCMP.o : ./SubType.hi
TermCMP.o : ./ErrorT.hi
TermCMP.o : ./HasName.hi
TermCMP.o : ./SemMonad.hi
TermCMP.o : ./ParseLib.hi
TermCMP.o : ./HasParser.hi
TermCMP.o : ./ShowUtils.hi
TermD.o : TermD.hs
TermD.o : ./Basics.hi
TermD.o : ./Fix.hi
TermD.o : ./MFix.hi
TermD.o : ./SubType.hi
TermD.o : ./ErrorT.hi
TermD.o : ./StateT.hi
TermD.o : ./EnvT.hi
TermD.o : ./HasName.hi
TermD.o : ./SemMonad.hi
TermD.o : ./ParseLib.hi
TermD.o : ./HasParser.hi
TermD.o : ./ShowUtils.hi
TermD.o : ./Heap.hi
TermD.o : ./Table.hi
TermF.o : TermF.hs
TermF.o : ./Fix.hi
TermF.o : ./Basics.hi
TermF.o : ./HasName.hi
TermF.o : ./MFix.hi
TermF.o : ./SubType.hi
TermF.o : ./ErrorT.hi
TermF.o : ./StateT.hi
TermF.o : ./EnvT.hi
TermF.o : ./Table.hi
TermF.o : ./Heap.hi
TermF.o : ./SemMonad.hi
TermF.o : ./ParseLib.hi
TermF.o : ./HasParser.hi
TermF.o : ./IOT.hi
TermN.o : TermN.hs
TermN.o : ./Id.hi
TermN.o : ./Fix.hi
TermN.o : ./SubType.hi
TermN.o : ./ErrorT.hi
TermN.o : ./HasName.hi
TermN.o : ./SemMonad.hi
TermN.o : ./ParseLib.hi
TermN.o : ./ShowUtils.hi
TermN.o : ./HasParser.hi
TermN.o : ./MFix.hi
TermN.o : ./Fix.hi
TermP.o : TermP.hs
TermP.o : ./Basics.hi
TermP.o : ./Fix.hi
TermP.o : ./MFix.hi
TermP.o : ./SubType.hi
TermP.o : ./ErrorT.hi
TermP.o : ./StateT.hi
TermP.o : ./EnvT.hi
TermP.o : ./IOT.hi
TermP.o : ./Table.hi
TermP.o : ./Heap.hi
TermP.o : ./HasName.hi
TermP.o : ./ParseLib.hi
TermP.o : ./HasParser.hi
TermP.o : ./SemMonad.hi
TermR.o : TermR.hs
TermR.o : ./HasName.hi
TermR.o : ./StateT.hi
TermR.o : ./Fix.hi
TermR.o : ./MFix.hi
TermR.o : ./SubType.hi
TermR.o : ./ErrorT.hi
TermR.o : ./ParseLib.hi
TermR.o : ./ShowUtils.hi
TermR.o : ./HasParser.hi
TermR.o : ./Basics.hi
TermR.o : ./Heap.hi
TermR.o : ./SemMonad.hi
TermV.o : TermV.hs
TermV.o : ./Basics.hi
TermV.o : ./HasName.hi
TermV.o : ./StateT.hi
TermV.o : ./Fix.hi
TermV.o : ./MFix.hi
TermV.o : ./SubType.hi
TermV.o : ./ErrorT.hi
TermV.o : ./EnvT.hi
TermV.o : ./Table.hi
TermV.o : ./Heap.hi
TermV.o : ./SemMonad.hi
TermV.o : ./ParseLib.hi
TermV.o : ./HasParser.hi
TermV.o : ./IOT.hi
# DO NOT DELETE: End of Haskell dependencies
